function menu(nga, admin) {
    return nga.menu()
        .addChild(nga.menu()
            .title('Member')
            .icon('<span class="fa fa-users fa-fw"></span>')
            .active(path => path.indexOf('/member') === 0) // active() is the function that determines if the menu is active
            .addChild(nga.menu()
                .title('會員列表')
                .link('/memberList/list?_page=1') // use the same entity list for several menu items
                .icon('<span class="fa fa-user-times fa-fw"></span>')) // no active() function => will never appear active
            .addChild(nga.menu()
                .title('Customers')
                .link('/customers/list?search={"has_ordered":"true"}') // use the same entity list for several menu items
                .icon('<span class="fa fa-user fa-fw"></span>'))
            .addChild(nga.menu()
                .title('Segments')
                .link('/segments') // this state isn't handled by ng-admin - no problem
                .active(path => path == '/segments')
                .icon('<span class="fa fa-scissors fa-fw"></span>'))
        )
        .addChild(nga.menu()
            .title('Restaurant')
            .icon('<span class="fa fa-shopping-cart fa-fw"></span>')
            .active(path => path.indexOf('/restaurant') === 0)
            .addChild(nga.menu()
                .title('餐廳列表')
                .link('/restaurantList/list?_page=1')
                .icon('<span class="fa fa-credit-card fa-fw"></span>'))
            .addChild(nga.menu()
                .title('Invoices')
                .link('/commands/list?search={"status":"delivered"}')
                .icon('<span class="fa fa-usd fa-fw"></span>'))
            .addChild(nga.menu()
                .title('Cancels')
                .link('/commands/list?search={"status":"cancelled"}')
                .icon('<span class="fa fa-hand-o-left fa-fw"></span>'))
        )
        .addChild(nga.menu()
            .title('Configuration')
            .icon('<span class="fa fa-cog fa-fw"></span>')
            .link('/settings/show/1')
            .active(path => path.indexOf('/settings') === 0)
        )
    ;
}
